config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  resources :exchange_rates, only: :index

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/exchange_rate.rb
class ExchangeRate < ApplicationRecord
  validates :symbol, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/exchange_rates_controller.rb
class ExchangeRatesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index]

  require 'rest-client'

  def index
    url = "https://blockchain.info/ticker"
    response = RestClient.get(url)

    render json: response

  end

  # def show
  #   @rate = Rate.find(params[:id])
  # end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/exchange_rates/index.html.erb
<div class="container">
  <div class="header d-flex my-3 p-3">
    Exchange Rates
  </div>

  <div class="row">
    <div class="col-12">


    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mara-Investments</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<%# banner %>
<div class="banner d-flex justify-content-center align-items-center h-90" style= "background-image: linear-gradient(rgba(0,0,0,0.2),rgba(0,0,0,0.1)), url('https://github.com/Muhammadjoni/mara-investments/blob/master/app/assets/images/male-model.jpg?raw=true'); height: 85vh;">
  <div class="brand">
    <img src="https://github.com/Muhammadjoni/mara-investments/blob/master/app/assets/images/vector.png?raw=true" id="vector"    />
    <img src="https://github.com/Muhammadjoni/mara-investments/blob/master/app/assets/images/m-vector.png?raw=true" style="margin-left: 1em; width: 25px; height: 25px;"/>
    <img src="https://github.com/Muhammadjoni/mara-investments/blob/master/app/assets/images/a-vector.png?raw=true" style="margin-left: 1em; width: 25px; height: 25px;"/>
    <img src="https://github.com/Muhammadjoni/mara-investments/blob/master/app/assets/images/r-vector.png?raw=true" style="margin-left: 1em; width: 25px; height: 25px;"/>
    <img src="https://github.com/Muhammadjoni/mara-investments/blob/master/app/assets/images/a-vector.png?raw=true" style="margin-left: 1em; width: 25px; height: 25px;"/>
  </div>

  <div class="text-center container">
    <div class="row" style="margin-top: 150px;">
      <div class="head-text col-md-6 text-left">
        <h1> <%= link_to "Investing,", exchange_rates_path%> </h1>
        <h1>for Africa</h1><br>
        <h3>Secure, multi-currency <br>
        investments.</h3>

        <div class="download">
          <img src="https://github.com/Muhammadjoni/mara-investments/blob/master/app/assets/images/appstore.png?raw=true" />
          <img src="https://github.com/Muhammadjoni/mara-investments/blob/master/app/assets/images/googleplay.png?raw=true" style="margin-left: 1em;" />
        </div>

      </div>
    </div>
  </div>
</div>

<%# partners %>

<div class="row partners">
  <div class="partners-links">
    <a href="#"><img src="https://github.com/Muhammadjoni/mara-investments/blob/master/app/assets/images/ftx.png?raw=true" /></a>
    <a href="#"><img src="https://github.com/Muhammadjoni/mara-investments/blob/master/app/assets/images/coinbase.png?raw=true" /></a>
    <a href="#"><img src="https://github.com/Muhammadjoni/mara-investments/blob/master/app/assets/images/haskey.png?raw=true" /></a>
    <a href="#"><img src="https://github.com/Muhammadjoni/mara-investments/blob/master/app/assets/images/tq.png?raw=true" /></a>
    <a href="#"><img src="https://github.com/Muhammadjoni/mara-investments/blob/master/app/assets/images/fundamental-labs.png?raw=truev" /></a>
    <a href="#"><img src="https://github.com/Muhammadjoni/mara-investments/blob/master/app/assets/images/woodstock.png?raw=truev" /></a>
    <a href="#"><img src="https://github.com/Muhammadjoni/mara-investments/blob/master/app/assets/images/distributed-global.png?raw=truev" /></a>
  </div>